version: 
  '3.3'
services:
  mysql_dissemination:
    build:
      ./docker_images/mysql/
    container_name:
      sdmx_db_mysql_dissemination
    command: 
      mysqld --default-authentication-plugin=mysql_native_password
    env_file: 
      ./secrets/mysql_env
    volumes:
      - sdmx_db_mysql_dissemination_data:/var/lib/mysql
    ports:
      - "3001:3306"
    restart:
      on-failure

  tomcat:
    build:
      ./docker_images/tomcat/
    container_name:
      sdmx_server_tomcat
    ports:
      - '8080:8080'
    volumes:
      - ./docker_images/tomcat/conf/nsi-jax-ws.xml:/usr/local/tomcat/conf/Catalina/localhost/nsi-jax-ws.xml
      - ./webapps/nsi-jax-ws.war:/usr/local/tomcat/webapps/nsi-jax-ws.war
      - ./docker_images/tomcat/bin/nsi-client:/usr/local/tomcat/nsi-client
      - ./docker_images/tomcat/bin/params:/usr/local/tomcat/params
      - ./webapps/nsi-client.war:/usr/local/tomcat/webapps/nsi-client.war
    links:
      - mysql_dissemination
    depends_on:
      - mysql_dissemination
    restart:
      on-failure

volumes:
  sdmx_db_mysql_dissemination_data:
